// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organization_id_or_slug}\preprodartifacts\snapshots\latest-base
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LatestBaseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LatestBaseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/preprodartifacts/snapshots/latest-base?app_id={app_id}{&branch*,compact_metadata*,project*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LatestBaseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/preprodartifacts/snapshots/latest-base?app_id={app_id}{&branch*,compact_metadata*,project*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve the most recent base snapshot for a given app.A base snapshot is one uploaded without a `base_sha` (i.e., a snapshotfrom a base branch like `main`). Use the optional `branch` and `project`parameters to narrow the search.The response includes the full image list with download URLs. Use`compact_metadata=1` to reduce image metadata.This endpoint requires a bearer token with `project:read` access.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.RetrieveLatestBaseSnapshot200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.RetrieveLatestBaseSnapshot200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder.LatestBaseRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.RetrieveLatestBaseSnapshot200> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder.LatestBaseRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sentry.OpenApiClient.Models.RetrieveLatestBaseSnapshot200>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.RetrieveLatestBaseSnapshot200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve the most recent base snapshot for a given app.A base snapshot is one uploaded without a `base_sha` (i.e., a snapshotfrom a base branch like `main`). Use the optional `branch` and `project`parameters to narrow the search.The response includes the full image list with download URLs. Use`compact_metadata=1` to reduce image metadata.This endpoint requires a bearer token with `project:read` access.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder.LatestBaseRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder.LatestBaseRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Preprodartifacts.Snapshots.LatestBase.LatestBaseRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve the most recent base snapshot for a given app.A base snapshot is one uploaded without a `base_sha` (i.e., a snapshotfrom a base branch like `main`). Use the optional `branch` and `project`parameters to narrow the search.The response includes the full image list with download URLs. Use`compact_metadata=1` to reduce image metadata.This endpoint requires a bearer token with `project:read` access.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LatestBaseRequestBuilderGetQueryParameters 
        {
            /// <summary>App identifier to match.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("app_id")]
            public string? AppId { get; set; }
#nullable restore
#else
            [QueryParameter("app_id")]
            public string AppId { get; set; }
#endif
            /// <summary>Git branch name to filter on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("branch")]
            public string? Branch { get; set; }
#nullable restore
#else
            [QueryParameter("branch")]
            public string Branch { get; set; }
#endif
            /// <summary>Set to &apos;1&apos; or &apos;true&apos; to strip image metadata to display_name, image_file_name, group, description, and image_url only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("compact_metadata")]
            public string? CompactMetadata { get; set; }
#nullable restore
#else
            [QueryParameter("compact_metadata")]
            public string CompactMetadata { get; set; }
#endif
            /// <summary>Project ID to scope the lookup.</summary>
            [QueryParameter("project")]
            public int? Project { get; set; }
        }
    }
}
#pragma warning restore CS0618
