// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Sentry.OpenApiClient.api.Zero.projects.item collection</summary>
        /// <param name="position">The ID or slug of the organization the resource belongs to.</param>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.WithOrganization_id_or_slugItemRequestBuilder"/></returns>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.WithOrganization_id_or_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("organization_id_or_slug", position);
                return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.WithOrganization_id_or_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/projects", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/projects", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
