// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organizationIdOrSlug}\events-dropped
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsDroppedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsDroppedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organizationIdOrSlug}/events-dropped?dataset={dataset}{&end*,environment*,interval*,outcome*,project*,reason*,start*,statsPeriod*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsDroppedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organizationIdOrSlug}/events-dropped?dataset={dataset}{&end*,environment*,interval*,outcome*,project*,reason*,start*,statsPeriod*}", rawUrl)
        {
        }
        /// <summary>
        /// **Experimental:** This API is under active development and may change.Return the events Sentry received but dropped (rate limited, filtered,invalid, abuse, client discarded, cardinality limited) bucketed over therequested interval, alongside the accepted volume per bucket so a callercan compute the dropped share.Select the dropped-data type with ``dataset`` and the bucket size with``interval``. Optionally scope the dropped side to one classification with``outcome`` (top-level) and/or ``reason`` (sub-classification within anoutcome); the accepted volume is always returned in full.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDropped200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDropped200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder.EventsDroppedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDropped200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder.EventsDroppedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDropped200Response>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDropped200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **Experimental:** This API is under active development and may change.Return the events Sentry received but dropped (rate limited, filtered,invalid, abuse, client discarded, cardinality limited) bucketed over therequested interval, alongside the accepted volume per bucket so a callercan compute the dropped share.Select the dropped-data type with ``dataset`` and the bucket size with``interval``. Optionally scope the dropped side to one classification with``outcome`` (top-level) and/or ``reason`` (sub-classification within anoutcome); the accepted volume is always returned in full.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder.EventsDroppedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder.EventsDroppedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.EventsDropped.EventsDroppedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// **Experimental:** This API is under active development and may change.Return the events Sentry received but dropped (rate limited, filtered,invalid, abuse, client discarded, cardinality limited) bucketed over therequested interval, alongside the accepted volume per bucket so a callercan compute the dropped share.Select the dropped-data type with ``dataset`` and the bucket size with``interval``. Optionally scope the dropped side to one classification with``outcome`` (top-level) and/or ``reason`` (sub-classification within anoutcome); the accepted volume is always returned in full.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsDroppedRequestBuilderGetQueryParameters 
        {
            /// <summary>Which dataset to query. The chosen dataset determines which fields are queryable.- `errors` - Error events.- `logs` - Structured log events.- `profile_functions` - Function-level Profiling data.- `spans` - Distributed tracing span events.- `tracemetrics` - Application Metrics.- `uptime_results` - Uptime monitoring check results.</summary>
            [QueryParameter("dataset")]
            public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDroppedDatasetParameter? Dataset { get; set; }
            /// <summary>The end of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("end")]
            public DateTimeOffset? End { get; set; }
            /// <summary>The name of environments to filter by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment")]
            public string[]? Environment { get; set; }
#nullable restore
#else
            [QueryParameter("environment")]
            public string[] Environment { get; set; }
#endif
            /// <summary>The size of the bucket for the timeseries to have, must be a value smaller than the window beingqueried. If the interval is invalid a default interval will be selected instead</summary>
            [QueryParameter("interval")]
            public int? Interval { get; set; }
            /// <summary>Narrow the dropped events (only) to a single top-level drop classification (e.g. `rate_limited`, `filtered`).* `filtered`* `rate_limited`* `invalid`* `abuse`* `client_discard`* `cardinality_limited`</summary>
            [QueryParameter("outcome")]
            public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationEventsDroppedOutcomeParameter? Outcome { get; set; }
            /// <summary>The IDs or slugs of projects to filter by. Project slugs are unique within each organization. Omit this parameter to include all accessible projects. `-1` is also accepted to include all accessible projects.For example, the following are valid parameters:- `/?project=1234&amp;project=56789`- `/?project=android&amp;project=javascript-react`- `/?project=-1`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public string[]? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public string[] Project { get; set; }
#endif
            /// <summary>Narrow the dropped events to a single reason, the sub-classification within an outcome (e.g. `spike_protection` within `rate_limited`). Should be combined with `outcome`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("reason")]
            public string? Reason { get; set; }
#nullable restore
#else
            [QueryParameter("reason")]
            public string Reason { get; set; }
#endif
            /// <summary>The start of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("start")]
            public DateTimeOffset? Start { get; set; }
            /// <summary>The period of time for the query, will override the start &amp; end parameters, a number followed by one of:- `d` for days- `h` for hours- `m` for minutes- `s` for seconds- `w` for weeksFor example, `24h`, to mean query data starting from 24 hours ago to now.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("statsPeriod")]
            public string? StatsPeriod { get; set; }
#nullable restore
#else
            [QueryParameter("statsPeriod")]
            public string StatsPeriod { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
