// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Environments;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Events;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Files;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Filters;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Hooks;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Issues;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Keys;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Members;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Monitors;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Ownership;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Preprod;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Preprodartifacts;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Profiling;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Releases;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Replays;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Repo;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Stats;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.SymbolSources;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Tags;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Teams;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.UserFeedback;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Users;
using Soenneker.Sentry.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\projects\{organizationIdOrSlug}\{projectIdOrSlug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectIdOrSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The environments property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Environments.EnvironmentsRequestBuilder Environments
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Environments.EnvironmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filters property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Filters.FiltersRequestBuilder Filters
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Filters.FiltersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hooks property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Hooks.HooksRequestBuilder Hooks
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Hooks.HooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Issues.IssuesRequestBuilder Issues
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Members.MembersRequestBuilder Members
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The monitors property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Monitors.MonitorsRequestBuilder Monitors
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Monitors.MonitorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ownership property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Ownership.OwnershipRequestBuilder Ownership
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Ownership.OwnershipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preprod property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Preprod.PreprodRequestBuilder Preprod
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Preprod.PreprodRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preprodartifacts property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Preprodartifacts.PreprodartifactsRequestBuilder Preprodartifacts
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Preprodartifacts.PreprodartifactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profiling property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Profiling.ProfilingRequestBuilder Profiling
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Profiling.ProfilingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releases property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Releases.ReleasesRequestBuilder Releases
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Releases.ReleasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replays property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Replays.ReplaysRequestBuilder Replays
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Replays.ReplaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repo property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Repo.RepoRequestBuilder Repo
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Repo.RepoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Stats.StatsRequestBuilder Stats
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The symbolSources property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.SymbolSources.SymbolSourcesRequestBuilder SymbolSources
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.SymbolSources.SymbolSourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userFeedback property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.UserFeedback.UserFeedbackRequestBuilder UserFeedback
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.UserFeedback.UserFeedbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.WithProjectIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectIdOrSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/projects/{organizationIdOrSlug}/{projectIdOrSlug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.WithProjectIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectIdOrSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/projects/{organizationIdOrSlug}/{projectIdOrSlug}", rawUrl)
        {
        }
        /// <summary>
        /// Schedules a project for deletion.Deletion happens asynchronously and therefore is not immediate. However once deletion hasbegun the state of a project changes and will be hidden from most public views.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return details on an individual project.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetProject200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.GetProject200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.GetProject200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sentry.OpenApiClient.Models.GetProject200Response>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.GetProject200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update various attributes and configurable settings for the given project.Note that solely having the **`project:read`** scope restricts updatable settings to`isBookmarked`, `autofixAutomationTuning`, `seerScannerAutomation`,`preprodSizeStatusChecksEnabled`, `preprodSizeStatusChecksRules`,`preprodSizeEnabledQuery`, `preprodDistributionEnabledQuery`,`preprodSizeEnabledByCustomer`, `preprodDistributionEnabledByCustomer`,and `preprodDistributionPrCommentsEnabledByCustomer`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.UpdateProject200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.UpdateProject200Response?> PutAsync(global::Soenneker.Sentry.OpenApiClient.Models.UpdateProjectRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.UpdateProject200Response> PutAsync(global::Soenneker.Sentry.OpenApiClient.Models.UpdateProjectRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sentry.OpenApiClient.Models.UpdateProject200Response>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.UpdateProject200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Schedules a project for deletion.Deletion happens asynchronously and therefore is not immediate. However once deletion hasbegun the state of a project changes and will be hidden from most public views.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Return details on an individual project.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update various attributes and configurable settings for the given project.Note that solely having the **`project:read`** scope restricts updatable settings to`isBookmarked`, `autofixAutomationTuning`, `seerScannerAutomation`,`preprodSizeStatusChecksEnabled`, `preprodSizeStatusChecksRules`,`preprodSizeEnabledQuery`, `preprodDistributionEnabledQuery`,`preprodSizeEnabledByCustomer`, `preprodDistributionEnabledByCustomer`,and `preprodDistributionPrCommentsEnabledByCustomer`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Sentry.OpenApiClient.Models.UpdateProjectRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Sentry.OpenApiClient.Models.UpdateProjectRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.WithProjectIdOrSlugItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.WithProjectIdOrSlugItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Projects.Item.Item.WithProjectIdOrSlugItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
