// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeleteSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "freq")]
        #pragma warning disable CS1591
        Freq,
        #pragma warning restore CS1591
        [EnumMember(Value = "inbox")]
        #pragma warning disable CS1591
        Inbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        New,
        #pragma warning restore CS1591
        [EnumMember(Value = "trends")]
        #pragma warning disable CS1591
        Trends,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
