// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organization_id_or_slug}\issues\
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmptyPathSegmentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmptyPathSegmentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/issues/{?collapse*,cursor*,end*,environment*,expand*,groupStatsPeriod*,id*,limit*,project*,query*,shortIdLookup*,sort*,start*,statsPeriod*,viewId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmptyPathSegmentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/issues/{?collapse*,cursor*,end*,environment*,expand*,groupStatsPeriod*,id*,limit*,project*,query*,shortIdLookup*,sort*,start*,statsPeriod*,viewId*}", rawUrl)
        {
        }
        /// <summary>
        /// Permanently remove the given issues. If IDs are provided, queries and filtering will be ignored. If any IDs are out of scope, the data won&apos;t be mutated but the endpoint will still produce a successful response. For example, if no issues were found matching the criteria, a HTTP 204 is returned.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return a list of issues for an organization. All parameters are supplied as query string parameters. A default query of `is:unresolved` is applied. To return all results, use an empty query value (i.e. ``?query=`). 
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Sentry.OpenApiClient.Models.List_an_Organization_s_Issues_200&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Sentry.OpenApiClient.Models.List_an_Organization_s_Issues_200>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Sentry.OpenApiClient.Models.List_an_Organization_s_Issues_200>> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Sentry.OpenApiClient.Models.List_an_Organization_s_Issues_200>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.List_an_Organization_s_Issues_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Bulk mutate various attributes on a maxmimum of 1000 issues. - For non-status updates, the `id` query parameter is required. - For status updates, the `id` query parameter may be omitted to update issues that match the filtering. If any IDs are out of scope, the data won&apos;t be mutated but the endpoint will still produce a successful response. For example, if no issues were found matching the criteria, a HTTP 204 is returned.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues_200"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues_200?> PutAsync(global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues body, Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues_200> PutAsync(global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues body, Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues_200>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Permanently remove the given issues. If IDs are provided, queries and filtering will be ignored. If any IDs are out of scope, the data won&apos;t be mutated but the endpoint will still produce a successful response. For example, if no issues were found matching the criteria, a HTTP 204 is returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Return a list of issues for an organization. All parameters are supplied as query string parameters. A default query of `is:unresolved` is applied. To return all results, use an empty query value (i.e. ``?query=`). 
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Bulk mutate various attributes on a maxmimum of 1000 issues. - For non-status updates, the `id` query parameter is required. - For status updates, the `id` query parameter may be omitted to update issues that match the filtering. If any IDs are out of scope, the data won&apos;t be mutated but the endpoint will still produce a successful response. For example, if no issues were found matching the criteria, a HTTP 204 is returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues body, Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Sentry.OpenApiClient.Models.Bulk_Mutate_an_Organization_s_Issues body, Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder.EmptyPathSegmentRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.EmptyPathSegmentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Permanently remove the given issues. If IDs are provided, queries and filtering will be ignored. If any IDs are out of scope, the data won&apos;t be mutated but the endpoint will still produce a successful response. For example, if no issues were found matching the criteria, a HTTP 204 is returned.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EmptyPathSegmentRequestBuilderDeleteQueryParameters 
        {
            /// <summary>The name of environments to filter by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment")]
            public string[]? Environment { get; set; }
#nullable restore
#else
            [QueryParameter("environment")]
            public string[] Environment { get; set; }
#endif
            /// <summary>The list of issue IDs to be removed. If not provided, it will attempt to remove the first 1000 issues.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public int?[]? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public int?[] Id { get; set; }
#endif
            /// <summary>The maximum number of issues to affect. The maximum is 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The IDs of projects to filter by. `-1` means all available projects.For example, the following are valid parameters:- `/?project=1234&amp;project=56789`- `/?project=-1`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public int?[]? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public int?[] Project { get; set; }
#endif
            /// <summary>An optional search query for filtering issues. A default query will apply if no view/query is set. For all results use this parameter with an empty string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>The sort order of the view. Options include &apos;Last Seen&apos; (`date`), &apos;First Seen&apos; (`new`), &apos;Trends&apos; (`trends`), &apos;Events&apos; (`freq`), &apos;Users&apos; (`user`), and &apos;Date Added&apos; (`inbox`).</summary>
            [QueryParameter("sort")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.DeleteSortQueryParameterType? Sort { get; set; }
            /// <summary>The ID of the view to use. If no query is present, the view&apos;s query and filters will be applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("viewId")]
            public string? ViewId { get; set; }
#nullable restore
#else
            [QueryParameter("viewId")]
            public string ViewId { get; set; }
#endif
        }
        /// <summary>
        /// Return a list of issues for an organization. All parameters are supplied as query string parameters. A default query of `is:unresolved` is applied. To return all results, use an empty query value (i.e. ``?query=`). 
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EmptyPathSegmentRequestBuilderGetQueryParameters 
        {
            /// <summary>Fields to remove from the response to improve query performance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("collapse")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetCollapseQueryParameterType[]? Collapse { get; set; }
#nullable restore
#else
            [QueryParameter("collapse")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetCollapseQueryParameterType[] Collapse { get; set; }
#endif
            /// <summary>A pointer to the last object fetched and its sort order; used to retrieve the next or previous results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>The end of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("end")]
            public DateTimeOffset? End { get; set; }
            /// <summary>The name of environments to filter by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment")]
            public string[]? Environment { get; set; }
#nullable restore
#else
            [QueryParameter("environment")]
            public string[] Environment { get; set; }
#endif
            /// <summary>Additional data to include in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetExpandQueryParameterType[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetExpandQueryParameterType[] Expand { get; set; }
#endif
            /// <summary>The timeline on which stats for the groups should be presented.</summary>
            [QueryParameter("groupStatsPeriod")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetGroupStatsPeriodQueryParameterType? GroupStatsPeriod { get; set; }
            /// <summary>The maximum number of issues to affect. The maximum is 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The IDs of projects to filter by. `-1` means all available projects.For example, the following are valid parameters:- `/?project=1234&amp;project=56789`- `/?project=-1`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public int?[]? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public int?[] Project { get; set; }
#endif
            /// <summary>An optional search query for filtering issues. A default query will apply if no view/query is set. For all results use this parameter with an empty string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>If this is set to `1` then the query will be parsed for issue short IDs. These may ignore other filters (e.g. projects), which is why it is an opt-in.</summary>
            [QueryParameter("shortIdLookup")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetShortIdLookupQueryParameterType? ShortIdLookup { get; set; }
            /// <summary>The sort order of the view. Options include &apos;Last Seen&apos; (`date`), &apos;First Seen&apos; (`new`), &apos;Trends&apos; (`trends`), &apos;Events&apos; (`freq`), &apos;Users&apos; (`user`), and &apos;Date Added&apos; (`inbox`).</summary>
            [QueryParameter("sort")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.GetSortQueryParameterType? Sort { get; set; }
            /// <summary>The start of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("start")]
            public DateTimeOffset? Start { get; set; }
            /// <summary>The period of time for the query, will override the start &amp; end parameters, a number followed by one of:- `d` for days- `h` for hours- `m` for minutes- `s` for seconds- `w` for weeksFor example, `24h`, to mean query data starting from 24 hours ago to now.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("statsPeriod")]
            public string? StatsPeriod { get; set; }
#nullable restore
#else
            [QueryParameter("statsPeriod")]
            public string StatsPeriod { get; set; }
#endif
            /// <summary>The ID of the view to use. If no query is present, the view&apos;s query and filters will be applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("viewId")]
            public string? ViewId { get; set; }
#nullable restore
#else
            [QueryParameter("viewId")]
            public string ViewId { get; set; }
#endif
        }
        /// <summary>
        /// Bulk mutate various attributes on a maxmimum of 1000 issues. - For non-status updates, the `id` query parameter is required. - For status updates, the `id` query parameter may be omitted to update issues that match the filtering. If any IDs are out of scope, the data won&apos;t be mutated but the endpoint will still produce a successful response. For example, if no issues were found matching the criteria, a HTTP 204 is returned.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EmptyPathSegmentRequestBuilderPutQueryParameters 
        {
            /// <summary>The name of environments to filter by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment")]
            public string[]? Environment { get; set; }
#nullable restore
#else
            [QueryParameter("environment")]
            public string[] Environment { get; set; }
#endif
            /// <summary>The list of issue IDs to mutate. It is optional for status updates, in which an implicit `update all` is assumed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public int?[]? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public int?[] Id { get; set; }
#endif
            /// <summary>The maximum number of issues to affect. The maximum is 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The IDs of projects to filter by. `-1` means all available projects.For example, the following are valid parameters:- `/?project=1234&amp;project=56789`- `/?project=-1`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public int?[]? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public int?[] Project { get; set; }
#endif
            /// <summary>An optional search query for filtering issues. A default query will apply if no view/query is set. For all results use this parameter with an empty string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>The sort order of the view. Options include &apos;Last Seen&apos; (`date`), &apos;First Seen&apos; (`new`), &apos;Trends&apos; (`trends`), &apos;Events&apos; (`freq`), &apos;Users&apos; (`user`), and &apos;Date Added&apos; (`inbox`).</summary>
            [QueryParameter("sort")]
            public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.PutSortQueryParameterType? Sort { get; set; }
            /// <summary>The ID of the view to use. If no query is present, the view&apos;s query and filters will be applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("viewId")]
            public string? ViewId { get; set; }
#nullable restore
#else
            [QueryParameter("viewId")]
            public string ViewId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
