// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organizationIdOrSlug}\profiling\flamegraph
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FlamegraphRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FlamegraphRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organizationIdOrSlug}/profiling/flamegraph{?dataSource*,end*,environment*,expand*,fingerprint*,project*,query*,start*,statsPeriod*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FlamegraphRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organizationIdOrSlug}/profiling/flamegraph{?dataSource*,end*,environment*,expand*,fingerprint*,project*,query*,start*,statsPeriod*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve an aggregated flamegraph for the organization, built from therequested data source (transactions, profiles, functions, or spans).Pass `expand=metrics` to include aggregated function metrics in the response.Requires profiling to be enabled for the organization.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraph200ResponseResponseJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraph200ResponseResponseJson?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder.FlamegraphRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraph200ResponseResponseJson> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder.FlamegraphRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraph200ResponseResponseJson>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraph200ResponseResponseJson.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve an aggregated flamegraph for the organization, built from therequested data source (transactions, profiles, functions, or spans).Pass `expand=metrics` to include aggregated function metrics in the response.Requires profiling to be enabled for the organization.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder.FlamegraphRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder.FlamegraphRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Profiling.Flamegraph.FlamegraphRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve an aggregated flamegraph for the organization, built from therequested data source (transactions, profiles, functions, or spans).Pass `expand=metrics` to include aggregated function metrics in the response.Requires profiling to be enabled for the organization.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FlamegraphRequestBuilderGetQueryParameters 
        {
            /// <summary>Source dataset to build the flamegraph from. Defaults to `functions` when `fingerprint` is set and `transactions` otherwise.</summary>
            [QueryParameter("dataSource")]
            public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraphDataSourceParameter? DataSource { get; set; }
            /// <summary>The end of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("end")]
            public DateTimeOffset? End { get; set; }
            /// <summary>The name of environments to filter by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment")]
            public string[]? Environment { get; set; }
#nullable restore
#else
            [QueryParameter("environment")]
            public string[] Environment { get; set; }
#endif
            /// <summary>Optional expansions. Pass `metrics` to include flamegraph metric aggregates in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraphExpandParameterItem[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationProfilingFlamegraphExpandParameterItem[] Expand { get; set; }
#endif
            /// <summary>A UInt32 function fingerprint. Only valid when `dataSource=functions`.</summary>
            [QueryParameter("fingerprint")]
            public int? Fingerprint { get; set; }
            /// <summary>The IDs or slugs of projects to filter by. Project slugs are unique within each organization. Omit this parameter to include all accessible projects. `-1` is also accepted to include all accessible projects.For example, the following are valid parameters:- `/?project=1234&amp;project=56789`- `/?project=android&amp;project=javascript-react`- `/?project=-1`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public string[]? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public string[] Project { get; set; }
#endif
            /// <summary>Sentry [search syntax](https://docs.sentry.io/concepts/search/) to filter the candidate profiles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>The start of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("start")]
            public DateTimeOffset? Start { get; set; }
            /// <summary>The period of time for the query, will override the start &amp; end parameters, a number followed by one of:- `d` for days- `h` for hours- `m` for minutes- `s` for seconds- `w` for weeksFor example, `24h`, to mean query data starting from 24 hours ago to now.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("statsPeriod")]
            public string? StatsPeriod { get; set; }
#nullable restore
#else
            [QueryParameter("statsPeriod")]
            public string StatsPeriod { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
