// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organizationIdOrSlug}\trace\{traceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTraceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTraceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organizationIdOrSlug}/trace/{traceId}{?additional_attributes*,end*,errorId*,include_uptime*,referrer*,start*,statsPeriod*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTraceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organizationIdOrSlug}/trace/{traceId}{?additional_attributes*,end*,errorId*,include_uptime*,referrer*,start*,statsPeriod*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve the spans, errors, and (optionally) uptime checks that make up a single trace.The response is a list of top-level events; each item may have nested `children`, `errors`,and `occurrences` arrays representing related items. Top-level entries are spans by defaultand may also be uptime checks when `include_uptime=1` is passed.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationTrace200ResponseResponseJsonItem&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationTrace200ResponseResponseJsonItem>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder.WithTraceItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationTrace200ResponseResponseJsonItem>> GetAsync(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder.WithTraceItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationTrace200ResponseResponseJsonItem>(requestInfo, global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationTrace200ResponseResponseJsonItem.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Retrieve the spans, errors, and (optionally) uptime checks that make up a single trace.The response is a list of top-level events; each item may have nested `children`, `errors`,and `occurrences` arrays representing related items. Top-level entries are spans by defaultand may also be uptime checks when `include_uptime=1` is passed.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder.WithTraceItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder.WithTraceItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Trace.Item.WithTraceItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve the spans, errors, and (optionally) uptime checks that make up a single trace.The response is a list of top-level events; each item may have nested `children`, `errors`,and `occurrences` arrays representing related items. Top-level entries are spans by defaultand may also be uptime checks when `include_uptime=1` is passed.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTraceItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Additional span attributes to include on each event. Repeat to request multiple.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("additional_attributes")]
            public string[]? AdditionalAttributes { get; set; }
#nullable restore
#else
            [QueryParameter("additional_attributes")]
            public string[] AdditionalAttributes { get; set; }
#endif
            /// <summary>The end of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("end")]
            public DateTimeOffset? End { get; set; }
            /// <summary>A 32-character hexadecimal event ID to bias the trace results toward including.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("errorId")]
            public string? ErrorId { get; set; }
#nullable restore
#else
            [QueryParameter("errorId")]
            public string ErrorId { get; set; }
#endif
            /// <summary>Set to `1` to include uptime check results in the trace. Defaults to `0`.</summary>
            [QueryParameter("include_uptime")]
            public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationTraceIncludeUptimeParameter? IncludeUptime { get; set; }
            /// <summary>Internal referrer identifier used for query tracing. Most clients can omit this.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("referrer")]
            public string? Referrer { get; set; }
#nullable restore
#else
            [QueryParameter("referrer")]
            public string Referrer { get; set; }
#endif
            /// <summary>The start of the period of time for the query, expected in ISO-8601 format. For example, `2001-12-14T12:34:56.7890`.</summary>
            [QueryParameter("start")]
            public DateTimeOffset? Start { get; set; }
            /// <summary>The period of time for the query, will override the start &amp; end parameters, a number followed by one of:- `d` for days- `h` for hours- `m` for minutes- `s` for seconds- `w` for weeksFor example, `24h`, to mean query data starting from 24 hours ago to now.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("statsPeriod")]
            public string? StatsPeriod { get; set; }
#nullable restore
#else
            [QueryParameter("statsPeriod")]
            public string StatsPeriod { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
