// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>The source&apos;s casing rules.* `lowercase`* `uppercase`* `default`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddASymbolSourceToAProject_layout_casing
    {
        [EnumMember(Value = "lowercase")]
        #pragma warning disable CS1591
        Lowercase,
        #pragma warning restore CS1591
        [EnumMember(Value = "uppercase")]
        #pragma warning disable CS1591
        Uppercase,
        #pragma warning restore CS1591
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
    }
}
