// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>&quot;The organization-level role of the new member. Roles include:* `billing` - Can manage payment and compliance details.* `member` - Can view and act on events, as well as view most other data within the organization.* `manager` - Has full management access to all teams and projects. Can also manage        the organization&apos;s membership.* `owner` - Has unrestricted access to the organization, its data, and its        settings. Can add, modify, and delete projects and members, as well as        make billing and plan changes.* `admin` - Can edit global integrations, manage projects, and add/remove teams.        They automatically assume the Team Admin role for teams they join.        Note: This role can no longer be assigned in Business and Enterprise plans. Use `TeamRoles` instead.        &quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddAMemberToAnOrganization_orgRole
    {
        [EnumMember(Value = "billing")]
        #pragma warning disable CS1591
        Billing,
        #pragma warning restore CS1591
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "manager")]
        #pragma warning disable CS1591
        Manager,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
    }
}
