// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>* `line`* `area`* `stacked_area`* `bar`* `table`* `big_number`* `top_n`* `details`* `categorical_bar`* `wheel`* `rage_and_dead_clicks`* `server_tree`* `text`* `agents_traces_table`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateANewDashboardForAnOrganization_widgets_display_type
    {
        [EnumMember(Value = "line")]
        #pragma warning disable CS1591
        Line,
        #pragma warning restore CS1591
        [EnumMember(Value = "area")]
        #pragma warning disable CS1591
        Area,
        #pragma warning restore CS1591
        [EnumMember(Value = "stacked_area")]
        #pragma warning disable CS1591
        Stacked_area,
        #pragma warning restore CS1591
        [EnumMember(Value = "bar")]
        #pragma warning disable CS1591
        Bar,
        #pragma warning restore CS1591
        [EnumMember(Value = "table")]
        #pragma warning disable CS1591
        Table,
        #pragma warning restore CS1591
        [EnumMember(Value = "big_number")]
        #pragma warning disable CS1591
        Big_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "top_n")]
        #pragma warning disable CS1591
        Top_n,
        #pragma warning restore CS1591
        [EnumMember(Value = "details")]
        #pragma warning disable CS1591
        Details,
        #pragma warning restore CS1591
        [EnumMember(Value = "categorical_bar")]
        #pragma warning disable CS1591
        Categorical_bar,
        #pragma warning restore CS1591
        [EnumMember(Value = "wheel")]
        #pragma warning disable CS1591
        Wheel,
        #pragma warning restore CS1591
        [EnumMember(Value = "rage_and_dead_clicks")]
        #pragma warning disable CS1591
        Rage_and_dead_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "server_tree")]
        #pragma warning disable CS1591
        Server_tree,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "agents_traces_table")]
        #pragma warning disable CS1591
        Agents_traces_table,
        #pragma warning restore CS1591
    }
}
