// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Create_a_Monitor_201_environments_activeIncident : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The brokenNotice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident_brokenNotice? BrokenNotice { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident_brokenNotice BrokenNotice { get; set; }
#endif
        /// <summary>The resolvingTimestamp property</summary>
        public DateTimeOffset? ResolvingTimestamp { get; set; }
        /// <summary>The startingTimestamp property</summary>
        public DateTimeOffset? StartingTimestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident"/> and sets the default values.
        /// </summary>
        public Create_a_Monitor_201_environments_activeIncident()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brokenNotice", n => { BrokenNotice = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident_brokenNotice>(global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident_brokenNotice.CreateFromDiscriminatorValue); } },
                { "resolvingTimestamp", n => { ResolvingTimestamp = n.GetDateTimeOffsetValue(); } },
                { "startingTimestamp", n => { StartingTimestamp = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Monitor_201_environments_activeIncident_brokenNotice>("brokenNotice", BrokenNotice);
            writer.WriteDateTimeOffsetValue("resolvingTimestamp", ResolvingTimestamp);
            writer.WriteDateTimeOffsetValue("startingTimestamp", StartingTimestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
