// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>
    /// Django Rest Framework serializer for incoming NotificationAction API payloads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Create_a_Spike_Protection_Notification_Action : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the integration used as the notification service. See[List Integrations](https://docs.sentry.io/api/integrations/list-an-organizations-available-integrations/)to retrieve a full list of integrations.Required if **service_type** is `slack`, `pagerduty` or `opsgenie`.</summary>
        public int? IntegrationId { get; set; }
        /// <summary>List of projects slugs that the Notification Action is created for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Projects { get; set; }
#nullable restore
#else
        public List<string> Projects { get; set; }
#endif
        /// <summary>Service that is used for sending the notification.- `email`- `slack`- `sentry_notification`- `pagerduty`- `opsgenie`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceType { get; set; }
#nullable restore
#else
        public string ServiceType { get; set; }
#endif
        /// <summary>Name of the notification target, like a Slack channel name.Required if **service_type** is `slack` or `opsgenie`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetDisplay { get; set; }
#nullable restore
#else
        public string TargetDisplay { get; set; }
#endif
        /// <summary>ID of the notification target, like a Slack channel ID.Required if **service_type** is `slack` or `opsgenie`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetIdentifier { get; set; }
#nullable restore
#else
        public string TargetIdentifier { get; set; }
#endif
        /// <summary>&quot;Type of the trigger that causes the notification. The only supported trigger right now is: `spike-protection`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerType { get; set; }
#nullable restore
#else
        public string TriggerType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Spike_Protection_Notification_Action"/> and sets the default values.
        /// </summary>
        public Create_a_Spike_Protection_Notification_Action()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Spike_Protection_Notification_Action"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Spike_Protection_Notification_Action CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Create_a_Spike_Protection_Notification_Action();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "integration_id", n => { IntegrationId = n.GetIntValue(); } },
                { "projects", n => { Projects = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "service_type", n => { ServiceType = n.GetStringValue(); } },
                { "target_display", n => { TargetDisplay = n.GetStringValue(); } },
                { "target_identifier", n => { TargetIdentifier = n.GetStringValue(); } },
                { "trigger_type", n => { TriggerType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("integration_id", IntegrationId);
            writer.WriteCollectionOfPrimitiveValues<string>("projects", Projects);
            writer.WriteStringValue("service_type", ServiceType);
            writer.WriteStringValue("target_display", TargetDisplay);
            writer.WriteStringValue("target_identifier", TargetIdentifier);
            writer.WriteStringValue("trigger_type", TriggerType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
