// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>
    /// Allows parameters to be defined in snake case, but passed as camel case.Errors are output in camel case.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EditAnOrganizationSCustomDashboard : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The saved end time for this dashboard.</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>The saved environment filter for this dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Environment { get; set; }
#nullable restore
#else
        public List<string> Environment { get; set; }
#endif
        /// <summary>The saved filters for this dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_filters? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_filters Filters { get; set; }
#endif
        /// <summary>A dashboard&apos;s unique id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The saved time range period for this dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Period { get; set; }
#nullable restore
#else
        public string Period { get; set; }
#endif
        /// <summary>Permissions that restrict users from editing dashboards</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_permissions? Permissions { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_permissions Permissions { get; set; }
#endif
        /// <summary>The saved projects filter for this dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Projects { get; set; }
#nullable restore
#else
        public List<int?> Projects { get; set; }
#endif
        /// <summary>The saved start time for this dashboard.</summary>
        public DateTimeOffset? Start { get; set; }
        /// <summary>The user-defined dashboard title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Setting that lets you display saved time range for this dashboard in UTC.</summary>
        public bool? Utc { get; set; }
        /// <summary>A json list of widgets saved in this dashboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_widgets>? Widgets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_widgets> Widgets { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard"/> and sets the default values.
        /// </summary>
        public EditAnOrganizationSCustomDashboard()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "environment", n => { Environment = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_filters>(global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_filters.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "period", n => { Period = n.GetStringValue(); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_permissions>(global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_permissions.CreateFromDiscriminatorValue); } },
                { "projects", n => { Projects = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "start", n => { Start = n.GetDateTimeOffsetValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "utc", n => { Utc = n.GetBoolValue(); } },
                { "widgets", n => { Widgets = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_widgets>(global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_widgets.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteCollectionOfPrimitiveValues<string>("environment", Environment);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_filters>("filters", Filters);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("period", Period);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_permissions>("permissions", Permissions);
            writer.WriteCollectionOfPrimitiveValues<int?>("projects", Projects);
            writer.WriteDateTimeOffsetValue("start", Start);
            writer.WriteStringValue("title", Title);
            writer.WriteBoolValue("utc", Utc);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.EditAnOrganizationSCustomDashboard_widgets>("widgets", Widgets);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
