// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>
    /// Allows parameters to be defined in snake case, but passed as camel case.Errors are output in camel case.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Edit_an_Organization_s_Custom_Dashboard_widgets : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>* `auto`* `dataMin`</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_axis_range? AxisRange { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>* `line`* `area`* `stacked_area`* `bar`* `table`* `big_number`* `top_n`* `details`* `categorical_bar`* `wheel`* `rage_and_dead_clicks`* `server_tree`* `text`* `agents_traces_table`</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_display_type? DisplayType { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The interval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Interval { get; set; }
#nullable restore
#else
        public string Interval { get; set; }
#endif
        /// <summary>The layout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_layout? Layout { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_layout Layout { get; set; }
#endif
        /// <summary>* `default`* `breakdown`</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_legend_type? LegendType { get; set; }
        /// <summary>The limit property</summary>
        public int? Limit { get; set; }
        /// <summary>The queries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_queries>? Queries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_queries> Queries { get; set; }
#endif
        /// <summary>The thresholds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_thresholds? Thresholds { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_thresholds Thresholds { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>* `discover`* `issue`* `metrics`* `error-events`* `transaction-like`* `spans`* `logs`* `tracemetrics`* `preprod-app-size`</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_widget_type? WidgetType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets"/> and sets the default values.
        /// </summary>
        public Edit_an_Organization_s_Custom_Dashboard_widgets()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "axis_range", n => { AxisRange = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_axis_range>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "display_type", n => { DisplayType = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_display_type>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "interval", n => { Interval = n.GetStringValue(); } },
                { "layout", n => { Layout = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_layout>(global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_layout.CreateFromDiscriminatorValue); } },
                { "legend_type", n => { LegendType = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_legend_type>(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "queries", n => { Queries = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_queries>(global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_queries.CreateFromDiscriminatorValue)?.AsList(); } },
                { "thresholds", n => { Thresholds = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_thresholds>(global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_thresholds.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "widget_type", n => { WidgetType = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_widget_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_axis_range>("axis_range", AxisRange);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_display_type>("display_type", DisplayType);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("interval", Interval);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_layout>("layout", Layout);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_legend_type>("legend_type", LegendType);
            writer.WriteIntValue("limit", Limit);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_queries>("queries", Queries);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_thresholds>("thresholds", Thresholds);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Edit_an_Organization_s_Custom_Dashboard_widgets_widget_type>("widget_type", WidgetType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
