// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationPreprodArtifactSnapshot200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The added property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseAddedItem>? Added { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseAddedItem> Added { get; set; }
#endif
        /// <summary>The added_count property</summary>
        public int? AddedCount { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The app_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The approval_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovalStatus { get; set; }
#nullable restore
#else
        public string ApprovalStatus { get; set; }
#endif
        /// <summary>The approvers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseApproversItem>? Approvers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseApproversItem> Approvers { get; set; }
#endif
        /// <summary>The base_artifact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseArtifactId { get; set; }
#nullable restore
#else
        public string BaseArtifactId { get; set; }
#endif
        /// <summary>The changed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseChangedItem>? Changed { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseChangedItem> Changed { get; set; }
#endif
        /// <summary>The changed_count property</summary>
        public int? ChangedCount { get; set; }
        /// <summary>The comparison_error_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComparisonErrorMessage { get; set; }
#nullable restore
#else
        public string ComparisonErrorMessage { get; set; }
#endif
        /// <summary>The comparison_state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComparisonState { get; set; }
#nullable restore
#else
        public string ComparisonState { get; set; }
#endif
        /// <summary>The comparison_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComparisonType { get; set; }
#nullable restore
#else
        public string ComparisonType { get; set; }
#endif
        /// <summary>The diff_threshold property</summary>
        public double? DiffThreshold { get; set; }
        /// <summary>The errored property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseErroredItem>? Errored { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseErroredItem> Errored { get; set; }
#endif
        /// <summary>The errored_count property</summary>
        public int? ErroredCount { get; set; }
        /// <summary>The head_artifact_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeadArtifactId { get; set; }
#nullable restore
#else
        public string HeadArtifactId { get; set; }
#endif
        /// <summary>The image_count property</summary>
        public int? ImageCount { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseImagesItem>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseImagesItem> Images { get; set; }
#endif
        /// <summary>The is_selective property</summary>
        public bool? IsSelective { get; set; }
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The removed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRemovedItem>? Removed { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRemovedItem> Removed { get; set; }
#endif
        /// <summary>The removed_count property</summary>
        public int? RemovedCount { get; set; }
        /// <summary>The renamed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRenamedItem>? Renamed { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRenamedItem> Renamed { get; set; }
#endif
        /// <summary>The renamed_count property</summary>
        public int? RenamedCount { get; set; }
        /// <summary>The skipped property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseSkippedItem>? Skipped { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseSkippedItem> Skipped { get; set; }
#endif
        /// <summary>The skipped_count property</summary>
        public int? SkippedCount { get; set; }
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The unchanged property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseUnchangedItem>? Unchanged { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseUnchangedItem> Unchanged { get; set; }
#endif
        /// <summary>The unchanged_count property</summary>
        public int? UnchangedCount { get; set; }
        /// <summary>The vcs_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseVcsInfo? VcsInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseVcsInfo VcsInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200Response"/> and sets the default values.
        /// </summary>
        public GetOrganizationPreprodArtifactSnapshot200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "added", n => { Added = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseAddedItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseAddedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "added_count", n => { AddedCount = n.GetIntValue(); } },
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "approval_status", n => { ApprovalStatus = n.GetStringValue(); } },
                { "approvers", n => { Approvers = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseApproversItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseApproversItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "base_artifact_id", n => { BaseArtifactId = n.GetStringValue(); } },
                { "changed", n => { Changed = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseChangedItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseChangedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "changed_count", n => { ChangedCount = n.GetIntValue(); } },
                { "comparison_error_message", n => { ComparisonErrorMessage = n.GetStringValue(); } },
                { "comparison_state", n => { ComparisonState = n.GetStringValue(); } },
                { "comparison_type", n => { ComparisonType = n.GetStringValue(); } },
                { "diff_threshold", n => { DiffThreshold = n.GetDoubleValue(); } },
                { "errored", n => { Errored = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseErroredItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseErroredItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errored_count", n => { ErroredCount = n.GetIntValue(); } },
                { "head_artifact_id", n => { HeadArtifactId = n.GetStringValue(); } },
                { "image_count", n => { ImageCount = n.GetIntValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseImagesItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseImagesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_selective", n => { IsSelective = n.GetBoolValue(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "removed", n => { Removed = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRemovedItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRemovedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "removed_count", n => { RemovedCount = n.GetIntValue(); } },
                { "renamed", n => { Renamed = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRenamedItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRenamedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "renamed_count", n => { RenamedCount = n.GetIntValue(); } },
                { "skipped", n => { Skipped = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseSkippedItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseSkippedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "skipped_count", n => { SkippedCount = n.GetIntValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "unchanged", n => { Unchanged = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseUnchangedItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseUnchangedItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "unchanged_count", n => { UnchangedCount = n.GetIntValue(); } },
                { "vcs_info", n => { VcsInfo = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseVcsInfo>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseVcsInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseAddedItem>("added", Added);
            writer.WriteIntValue("added_count", AddedCount);
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("approval_status", ApprovalStatus);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseApproversItem>("approvers", Approvers);
            writer.WriteStringValue("base_artifact_id", BaseArtifactId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseChangedItem>("changed", Changed);
            writer.WriteIntValue("changed_count", ChangedCount);
            writer.WriteStringValue("comparison_error_message", ComparisonErrorMessage);
            writer.WriteStringValue("comparison_state", ComparisonState);
            writer.WriteStringValue("comparison_type", ComparisonType);
            writer.WriteDoubleValue("diff_threshold", DiffThreshold);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseErroredItem>("errored", Errored);
            writer.WriteIntValue("errored_count", ErroredCount);
            writer.WriteStringValue("head_artifact_id", HeadArtifactId);
            writer.WriteIntValue("image_count", ImageCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseImagesItem>("images", Images);
            writer.WriteBoolValue("is_selective", IsSelective);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRemovedItem>("removed", Removed);
            writer.WriteIntValue("removed_count", RemovedCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseRenamedItem>("renamed", Renamed);
            writer.WriteIntValue("renamed_count", RenamedCount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseSkippedItem>("skipped", Skipped);
            writer.WriteIntValue("skipped_count", SkippedCount);
            writer.WriteStringValue("state", State);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseUnchangedItem>("unchanged", Unchanged);
            writer.WriteIntValue("unchanged_count", UnchangedCount);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationPreprodArtifactSnapshot200ResponseVcsInfo>("vcs_info", VcsInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
