// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrganizationIssueCollapseParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "release")]
        #pragma warning disable CS1591
        Release,
        #pragma warning restore CS1591
        [EnumMember(Value = "stats")]
        #pragma warning disable CS1591
        Stats,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
    }
}
