// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationSessions200ResponseGroupsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemBy? By { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemBy By { get; set; }
#endif
        /// <summary>The series property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemSeries? Series { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemSeries Series { get; set; }
#endif
        /// <summary>The totals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemTotals? Totals { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemTotals Totals { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItem"/> and sets the default values.
        /// </summary>
        public GetOrganizationSessions200ResponseGroupsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "by", n => { By = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemBy>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemBy.CreateFromDiscriminatorValue); } },
                { "series", n => { Series = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemSeries>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemSeries.CreateFromDiscriminatorValue); } },
                { "totals", n => { Totals = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemTotals>(global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemTotals.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemBy>("by", By);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemSeries>("series", Series);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetOrganizationSessions200ResponseGroupsItemTotals>("totals", Totals);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
