// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrganizationProfilingFlamegraphExpandParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "metrics")]
        #pragma warning disable CS1591
        Metrics,
        #pragma warning restore CS1591
    }
}
