// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetProjectEventSourceMapDebug200ResponseExceptionsItemFramesItemReleaseProcessSourceFileLookupResult
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "found")]
        #pragma warning disable CS1591
        Found,
        #pragma warning restore CS1591
        [EnumMember(Value = "wrong-dist")]
        #pragma warning disable CS1591
        WrongDist,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsuccessful")]
        #pragma warning disable CS1591
        Unsuccessful,
        #pragma warning restore CS1591
    }
}
