// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetProjectPreprodSnapshotStatusCheckRules200ResponseRules : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The failOnAdded property</summary>
        public bool? FailOnAdded { get; set; }
        /// <summary>The failOnChanged property</summary>
        public bool? FailOnChanged { get; set; }
        /// <summary>The failOnRemoved property</summary>
        public bool? FailOnRemoved { get; set; }
        /// <summary>The failOnRenamed property</summary>
        public bool? FailOnRenamed { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetProjectPreprodSnapshotStatusCheckRules200ResponseRules"/> and sets the default values.
        /// </summary>
        public GetProjectPreprodSnapshotStatusCheckRules200ResponseRules()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetProjectPreprodSnapshotStatusCheckRules200ResponseRules"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.GetProjectPreprodSnapshotStatusCheckRules200ResponseRules CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.GetProjectPreprodSnapshotStatusCheckRules200ResponseRules();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "failOnAdded", n => { FailOnAdded = n.GetBoolValue(); } },
                { "failOnChanged", n => { FailOnChanged = n.GetBoolValue(); } },
                { "failOnRemoved", n => { FailOnRemoved = n.GetBoolValue(); } },
                { "failOnRenamed", n => { FailOnRenamed = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("failOnAdded", FailOnAdded);
            writer.WriteBoolValue("failOnChanged", FailOnChanged);
            writer.WriteBoolValue("failOnRemoved", FailOnRemoved);
            writer.WriteBoolValue("failOnRenamed", FailOnRenamed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
