// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetProjectEvent200ResponseOccurrence : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Assignee { get; set; }
#nullable restore
#else
        public string Assignee { get; set; }
#endif
        /// <summary>The culprit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Culprit { get; set; }
#nullable restore
#else
        public string Culprit { get; set; }
#endif
        /// <summary>The detectionTime property</summary>
        public double? DetectionTime { get; set; }
        /// <summary>The eventId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventId { get; set; }
#nullable restore
#else
        public string EventId { get; set; }
#endif
        /// <summary>The evidenceData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceData? EvidenceData { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceData EvidenceData { get; set; }
#endif
        /// <summary>The evidenceDisplay property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceDisplayItem>? EvidenceDisplay { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceDisplayItem> EvidenceDisplay { get; set; }
#endif
        /// <summary>The fingerprint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Fingerprint { get; set; }
#nullable restore
#else
        public List<string> Fingerprint { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The issueTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssueTitle { get; set; }
#nullable restore
#else
        public string IssueTitle { get; set; }
#endif
        /// <summary>The level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The projectId property</summary>
        public int? ProjectId { get; set; }
        /// <summary>The resourceId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceId { get; set; }
#nullable restore
#else
        public string ResourceId { get; set; }
#endif
        /// <summary>The subtitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subtitle { get; set; }
#nullable restore
#else
        public string Subtitle { get; set; }
#endif
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrence"/> and sets the default values.
        /// </summary>
        public GetProjectEvent200ResponseOccurrence()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrence"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrence CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignee", n => { Assignee = n.GetStringValue(); } },
                { "culprit", n => { Culprit = n.GetStringValue(); } },
                { "detectionTime", n => { DetectionTime = n.GetDoubleValue(); } },
                { "eventId", n => { EventId = n.GetStringValue(); } },
                { "evidenceData", n => { EvidenceData = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceData>(global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceData.CreateFromDiscriminatorValue); } },
                { "evidenceDisplay", n => { EvidenceDisplay = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceDisplayItem>(global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceDisplayItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fingerprint", n => { Fingerprint = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "issueTitle", n => { IssueTitle = n.GetStringValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "projectId", n => { ProjectId = n.GetIntValue(); } },
                { "resourceId", n => { ResourceId = n.GetStringValue(); } },
                { "subtitle", n => { Subtitle = n.GetStringValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignee", Assignee);
            writer.WriteStringValue("culprit", Culprit);
            writer.WriteDoubleValue("detectionTime", DetectionTime);
            writer.WriteStringValue("eventId", EventId);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceData>("evidenceData", EvidenceData);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.GetProjectEvent200ResponseOccurrenceEvidenceDisplayItem>("evidenceDisplay", EvidenceDisplay);
            writer.WriteCollectionOfPrimitiveValues<string>("fingerprint", Fingerprint);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("issueTitle", IssueTitle);
            writer.WriteStringValue("level", Level);
            writer.WriteIntValue("priority", Priority);
            writer.WriteIntValue("projectId", ProjectId);
            writer.WriteStringValue("resourceId", ResourceId);
            writer.WriteStringValue("subtitle", Subtitle);
            writer.WriteIntValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
