// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetProjectEventSourceMapDebug200ResponseSdkDebugIdSupport
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "not-supported")]
        #pragma warning disable CS1591
        NotSupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "unofficial-sdk")]
        #pragma warning disable CS1591
        UnofficialSdk,
        #pragma warning restore CS1591
        [EnumMember(Value = "needs-upgrade")]
        #pragma warning disable CS1591
        NeedsUpgrade,
        #pragma warning restore CS1591
        [EnumMember(Value = "full")]
        #pragma warning disable CS1591
        Full,
        #pragma warning restore CS1591
    }
}
