// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListOrganizationTraceMetrics200ResponseSchemaItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemContext Context { get; set; }
#endif
        /// <summary>The count property</summary>
        public double? Count { get; set; }
        /// <summary>The lastSeen property</summary>
        public double? LastSeen { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemType? Type { get; set; }
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseSchemaItem"/> and sets the default values.
        /// </summary>
        public ListOrganizationTraceMetrics200ResponseSchemaItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseSchemaItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseSchemaItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseSchemaItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemContext>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemContext.CreateFromDiscriminatorValue); } },
                { "count", n => { Count = n.GetDoubleValue(); } },
                { "lastSeen", n => { LastSeen = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemType>(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemContext>("context", Context);
            writer.WriteDoubleValue("count", Count);
            writer.WriteDoubleValue("lastSeen", LastSeen);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationTraceMetrics200ResponseItemType>("type", Type);
            writer.WriteStringValue("unit", Unit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
