// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListAnOrganizationSSelectors200_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The count_dead_clicks property</summary>
        public int? CountDeadClicks { get; set; }
        /// <summary>The count_rage_clicks property</summary>
        public int? CountRageClicks { get; set; }
        /// <summary>The dom_element property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DomElement { get; set; }
#nullable restore
#else
        public string DomElement { get; set; }
#endif
        /// <summary>The element property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data_element? Element { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data_element Element { get; set; }
#endif
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data"/> and sets the default values.
        /// </summary>
        public ListAnOrganizationSSelectors200_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "count_dead_clicks", n => { CountDeadClicks = n.GetIntValue(); } },
                { "count_rage_clicks", n => { CountRageClicks = n.GetIntValue(); } },
                { "dom_element", n => { DomElement = n.GetStringValue(); } },
                { "element", n => { Element = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data_element>(global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data_element.CreateFromDiscriminatorValue); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("count_dead_clicks", CountDeadClicks);
            writer.WriteIntValue("count_rage_clicks", CountRageClicks);
            writer.WriteStringValue("dom_element", DomElement);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAnOrganizationSSelectors200_data_element>("element", Element);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
