// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListOrganizationTraceMetrics200ResponseItemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "counter")]
        #pragma warning disable CS1591
        Counter,
        #pragma warning restore CS1591
        [EnumMember(Value = "gauge")]
        #pragma warning disable CS1591
        Gauge,
        #pragma warning restore CS1591
        [EnumMember(Value = "distribution")]
        #pragma warning disable CS1591
        Distribution,
        #pragma warning restore CS1591
    }
}
