// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListOrganizationReplays200ResponseDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activity property</summary>
        public int? Activity { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The browser property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemBrowser? Browser { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemBrowser Browser { get; set; }
#endif
        /// <summary>The clicks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemClicksItem>? Clicks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemClicksItem> Clicks { get; set; }
#endif
        /// <summary>The count_dead_clicks property</summary>
        public int? CountDeadClicks { get; set; }
        /// <summary>The count_errors property</summary>
        public int? CountErrors { get; set; }
        /// <summary>The count_infos property</summary>
        public int? CountInfos { get; set; }
        /// <summary>The count_rage_clicks property</summary>
        public int? CountRageClicks { get; set; }
        /// <summary>The count_segments property</summary>
        public int? CountSegments { get; set; }
        /// <summary>The count_urls property</summary>
        public int? CountUrls { get; set; }
        /// <summary>The count_warnings property</summary>
        public int? CountWarnings { get; set; }
        /// <summary>The device property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemDevice? Device { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemDevice Device { get; set; }
#endif
        /// <summary>The dist property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dist { get; set; }
#nullable restore
#else
        public string Dist { get; set; }
#endif
        /// <summary>The duration property</summary>
        public int? Duration { get; set; }
        /// <summary>The environment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Environment { get; set; }
#nullable restore
#else
        public string Environment { get; set; }
#endif
        /// <summary>The error_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ErrorIds { get; set; }
#nullable restore
#else
        public List<string> ErrorIds { get; set; }
#endif
        /// <summary>The finished_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinishedAt { get; set; }
#nullable restore
#else
        public string FinishedAt { get; set; }
#endif
        /// <summary>The has_viewed property</summary>
        public bool? HasViewed { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_archived property</summary>
        public bool? IsArchived { get; set; }
        /// <summary>The os property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOs? Os { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOs Os { get; set; }
#endif
        /// <summary>The ota_updates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOtaUpdates? OtaUpdates { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOtaUpdates OtaUpdates { get; set; }
#endif
        /// <summary>The platform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The releases property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Releases { get; set; }
#nullable restore
#else
        public List<string> Releases { get; set; }
#endif
        /// <summary>The replay_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplayType { get; set; }
#nullable restore
#else
        public string ReplayType { get; set; }
#endif
        /// <summary>The sdk property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemSdk? Sdk { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemSdk Sdk { get; set; }
#endif
        /// <summary>The started_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemTags? Tags { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemTags Tags { get; set; }
#endif
        /// <summary>The trace_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TraceIds { get; set; }
#nullable restore
#else
        public List<string> TraceIds { get; set; }
#endif
        /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Urls { get; set; }
#nullable restore
#else
        public List<string> Urls { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public ListOrganizationReplays200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity", n => { Activity = n.GetIntValue(); } },
                { "browser", n => { Browser = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemBrowser>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemBrowser.CreateFromDiscriminatorValue); } },
                { "clicks", n => { Clicks = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemClicksItem>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemClicksItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "count_dead_clicks", n => { CountDeadClicks = n.GetIntValue(); } },
                { "count_errors", n => { CountErrors = n.GetIntValue(); } },
                { "count_infos", n => { CountInfos = n.GetIntValue(); } },
                { "count_rage_clicks", n => { CountRageClicks = n.GetIntValue(); } },
                { "count_segments", n => { CountSegments = n.GetIntValue(); } },
                { "count_urls", n => { CountUrls = n.GetIntValue(); } },
                { "count_warnings", n => { CountWarnings = n.GetIntValue(); } },
                { "device", n => { Device = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemDevice>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemDevice.CreateFromDiscriminatorValue); } },
                { "dist", n => { Dist = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "environment", n => { Environment = n.GetStringValue(); } },
                { "error_ids", n => { ErrorIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "finished_at", n => { FinishedAt = n.GetStringValue(); } },
                { "has_viewed", n => { HasViewed = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_archived", n => { IsArchived = n.GetBoolValue(); } },
                { "os", n => { Os = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOs>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOs.CreateFromDiscriminatorValue); } },
                { "ota_updates", n => { OtaUpdates = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOtaUpdates>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOtaUpdates.CreateFromDiscriminatorValue); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "releases", n => { Releases = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "replay_type", n => { ReplayType = n.GetStringValue(); } },
                { "sdk", n => { Sdk = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemSdk>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemSdk.CreateFromDiscriminatorValue); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemTags>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemTags.CreateFromDiscriminatorValue); } },
                { "trace_ids", n => { TraceIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "urls", n => { Urls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemUser>(global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activity", Activity);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemBrowser>("browser", Browser);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemClicksItem>("clicks", Clicks);
            writer.WriteIntValue("count_dead_clicks", CountDeadClicks);
            writer.WriteIntValue("count_errors", CountErrors);
            writer.WriteIntValue("count_infos", CountInfos);
            writer.WriteIntValue("count_rage_clicks", CountRageClicks);
            writer.WriteIntValue("count_segments", CountSegments);
            writer.WriteIntValue("count_urls", CountUrls);
            writer.WriteIntValue("count_warnings", CountWarnings);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemDevice>("device", Device);
            writer.WriteStringValue("dist", Dist);
            writer.WriteIntValue("duration", Duration);
            writer.WriteStringValue("environment", Environment);
            writer.WriteCollectionOfPrimitiveValues<string>("error_ids", ErrorIds);
            writer.WriteStringValue("finished_at", FinishedAt);
            writer.WriteBoolValue("has_viewed", HasViewed);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_archived", IsArchived);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOs>("os", Os);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemOtaUpdates>("ota_updates", OtaUpdates);
            writer.WriteStringValue("platform", Platform);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteCollectionOfPrimitiveValues<string>("releases", Releases);
            writer.WriteStringValue("replay_type", ReplayType);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemSdk>("sdk", Sdk);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemTags>("tags", Tags);
            writer.WriteCollectionOfPrimitiveValues<string>("trace_ids", TraceIds);
            writer.WriteCollectionOfPrimitiveValues<string>("urls", Urls);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListOrganizationReplays200ResponseDataItemUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
