// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListOrganizationDashboardsFilterParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "excludeFavorites")]
        #pragma warning disable CS1591
        ExcludeFavorites,
        #pragma warning restore CS1591
        [EnumMember(Value = "excludePrebuilt")]
        #pragma warning disable CS1591
        ExcludePrebuilt,
        #pragma warning restore CS1591
        [EnumMember(Value = "onlyFavorites")]
        #pragma warning disable CS1591
        OnlyFavorites,
        #pragma warning restore CS1591
        [EnumMember(Value = "onlyPrebuilt")]
        #pragma warning disable CS1591
        OnlyPrebuilt,
        #pragma warning restore CS1591
        [EnumMember(Value = "owned")]
        #pragma warning disable CS1591
        Owned,
        #pragma warning restore CS1591
        [EnumMember(Value = "shared")]
        #pragma warning disable CS1591
        Shared,
        #pragma warning restore CS1591
        [EnumMember(Value = "showHidden")]
        #pragma warning disable CS1591
        ShowHidden,
        #pragma warning restore CS1591
    }
}
