// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListAProjectSIssues200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The annotations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Annotations { get; set; }
#nullable restore
#else
        public List<string> Annotations { get; set; }
#endif
        /// <summary>The assignedTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_assignedTo? AssignedTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_assignedTo AssignedTo { get; set; }
#endif
        /// <summary>The count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Count { get; set; }
#nullable restore
#else
        public string Count { get; set; }
#endif
        /// <summary>The culprit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Culprit { get; set; }
#nullable restore
#else
        public string Culprit { get; set; }
#endif
        /// <summary>The firstSeen property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstSeen { get; set; }
#nullable restore
#else
        public string FirstSeen { get; set; }
#endif
        /// <summary>The hasSeen property</summary>
        public bool? HasSeen { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isBookmarked property</summary>
        public bool? IsBookmarked { get; set; }
        /// <summary>The isPublic property</summary>
        public bool? IsPublic { get; set; }
        /// <summary>The isSubscribed property</summary>
        public bool? IsSubscribed { get; set; }
        /// <summary>The lastSeen property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastSeen { get; set; }
#nullable restore
#else
        public string LastSeen { get; set; }
#endif
        /// <summary>The level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>The logger property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Logger { get; set; }
#nullable restore
#else
        public string Logger { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata Metadata { get; set; }
#endif
        /// <summary>The numComments property</summary>
        public int? NumComments { get; set; }
        /// <summary>The permalink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Permalink { get; set; }
#nullable restore
#else
        public string Permalink { get; set; }
#endif
        /// <summary>The project property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_project? Project { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_project Project { get; set; }
#endif
        /// <summary>The shareId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShareId { get; set; }
#nullable restore
#else
        public string ShareId { get; set; }
#endif
        /// <summary>The shortId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortId { get; set; }
#nullable restore
#else
        public string ShortId { get; set; }
#endif
        /// <summary>The stats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_stats? Stats { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_stats Stats { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_status? Status { get; set; }
        /// <summary>The statusDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_statusDetails? StatusDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_statusDetails StatusDetails { get; set; }
#endif
        /// <summary>The subscriptionDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_subscriptionDetails? SubscriptionDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_subscriptionDetails SubscriptionDetails { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The userCount property</summary>
        public int? UserCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200"/> and sets the default values.
        /// </summary>
        public ListAProjectSIssues200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "assignedTo", n => { AssignedTo = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_assignedTo>(global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_assignedTo.CreateFromDiscriminatorValue); } },
                { "count", n => { Count = n.GetStringValue(); } },
                { "culprit", n => { Culprit = n.GetStringValue(); } },
                { "firstSeen", n => { FirstSeen = n.GetStringValue(); } },
                { "hasSeen", n => { HasSeen = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isBookmarked", n => { IsBookmarked = n.GetBoolValue(); } },
                { "isPublic", n => { IsPublic = n.GetBoolValue(); } },
                { "isSubscribed", n => { IsSubscribed = n.GetBoolValue(); } },
                { "lastSeen", n => { LastSeen = n.GetStringValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "logger", n => { Logger = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata>(global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata.CreateFromDiscriminatorValue); } },
                { "numComments", n => { NumComments = n.GetIntValue(); } },
                { "permalink", n => { Permalink = n.GetStringValue(); } },
                { "project", n => { Project = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_project>(global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_project.CreateFromDiscriminatorValue); } },
                { "shareId", n => { ShareId = n.GetStringValue(); } },
                { "shortId", n => { ShortId = n.GetStringValue(); } },
                { "stats", n => { Stats = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_stats>(global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_stats.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_status>(); } },
                { "statusDetails", n => { StatusDetails = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_statusDetails>(global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_statusDetails.CreateFromDiscriminatorValue); } },
                { "subscriptionDetails", n => { SubscriptionDetails = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_subscriptionDetails>(global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_subscriptionDetails.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "userCount", n => { UserCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("annotations", Annotations);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_assignedTo>("assignedTo", AssignedTo);
            writer.WriteStringValue("count", Count);
            writer.WriteStringValue("culprit", Culprit);
            writer.WriteStringValue("firstSeen", FirstSeen);
            writer.WriteBoolValue("hasSeen", HasSeen);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isBookmarked", IsBookmarked);
            writer.WriteBoolValue("isPublic", IsPublic);
            writer.WriteBoolValue("isSubscribed", IsSubscribed);
            writer.WriteStringValue("lastSeen", LastSeen);
            writer.WriteStringValue("level", Level);
            writer.WriteStringValue("logger", Logger);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata>("metadata", Metadata);
            writer.WriteIntValue("numComments", NumComments);
            writer.WriteStringValue("permalink", Permalink);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_project>("project", Project);
            writer.WriteStringValue("shareId", ShareId);
            writer.WriteStringValue("shortId", ShortId);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_stats>("stats", Stats);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_statusDetails>("statusDetails", StatusDetails);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_subscriptionDetails>("subscriptionDetails", SubscriptionDetails);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("userCount", UserCount);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember1"/>, <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListAProjectSIssues200_metadata : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember1? ListAProjectSIssues200MetadataMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember1 ListAProjectSIssues200MetadataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember2? ListAProjectSIssues200MetadataMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember2 ListAProjectSIssues200MetadataMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200.ListAProjectSIssues200_metadata();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ListAProjectSIssues200MetadataMember1 = new global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ListAProjectSIssues200MetadataMember2 = new global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListAProjectSIssues200MetadataMember1 != null)
                {
                    return ListAProjectSIssues200MetadataMember1.GetFieldDeserializers();
                }
                else if(ListAProjectSIssues200MetadataMember2 != null)
                {
                    return ListAProjectSIssues200MetadataMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ListAProjectSIssues200MetadataMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember1>(null, ListAProjectSIssues200MetadataMember1);
                }
                else if(ListAProjectSIssues200MetadataMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.ListAProjectSIssues200_metadataMember2>(null, ListAProjectSIssues200MetadataMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
