// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Resolve_an_Event_ID_200_event : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The breakdowns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_breakdowns? Breakdowns { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_breakdowns Breakdowns { get; set; }
#endif
        /// <summary>The context property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_context? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_context Context { get; set; }
#endif
        /// <summary>The contexts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_contexts? Contexts { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_contexts Contexts { get; set; }
#endif
        /// <summary>The crashFile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CrashFile { get; set; }
#nullable restore
#else
        public string CrashFile { get; set; }
#endif
        /// <summary>The culprit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Culprit { get; set; }
#nullable restore
#else
        public string Culprit { get; set; }
#endif
        /// <summary>The dateCreated property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The dateReceived property</summary>
        public DateTimeOffset? DateReceived { get; set; }
        /// <summary>The dist property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dist { get; set; }
#nullable restore
#else
        public string Dist { get; set; }
#endif
        /// <summary>The endTimestamp property</summary>
        public DateTimeOffset? EndTimestamp { get; set; }
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_entries>? Entries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_entries> Entries { get; set; }
#endif
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_errors>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_errors> Errors { get; set; }
#endif
        /// <summary>The eventID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventID { get; set; }
#nullable restore
#else
        public string EventID { get; set; }
#endif
        /// <summary>The fingerprints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Fingerprints { get; set; }
#nullable restore
#else
        public List<string> Fingerprints { get; set; }
#endif
        /// <summary>The groupID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupID { get; set; }
#nullable restore
#else
        public string GroupID { get; set; }
#endif
        /// <summary>The groupingConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_groupingConfig? GroupingConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_groupingConfig GroupingConfig { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The measurements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_measurements? Measurements { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_measurements Measurements { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_meta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_meta Meta { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_metadata Metadata { get; set; }
#endif
        /// <summary>The occurrence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_occurrence? Occurrence { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_occurrence Occurrence { get; set; }
#endif
        /// <summary>The packages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_packages? Packages { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_packages Packages { get; set; }
#endif
        /// <summary>The platform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>The projectID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectID { get; set; }
#nullable restore
#else
        public string ProjectID { get; set; }
#endif
        /// <summary>The sdk property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_sdk? Sdk { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_sdk Sdk { get; set; }
#endif
        /// <summary>The size property</summary>
        public int? Size { get; set; }
        /// <summary>The startTimestamp property</summary>
        public DateTimeOffset? StartTimestamp { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_tags>? Tags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_tags> Tags { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_user? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event"/> and sets the default values.
        /// </summary>
        public Resolve_an_Event_ID_200_event()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "breakdowns", n => { Breakdowns = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_breakdowns>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_breakdowns.CreateFromDiscriminatorValue); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_context>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_context.CreateFromDiscriminatorValue); } },
                { "contexts", n => { Contexts = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_contexts>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_contexts.CreateFromDiscriminatorValue); } },
                { "crashFile", n => { CrashFile = n.GetStringValue(); } },
                { "culprit", n => { Culprit = n.GetStringValue(); } },
                { "dateCreated", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "dateReceived", n => { DateReceived = n.GetDateTimeOffsetValue(); } },
                { "dist", n => { Dist = n.GetStringValue(); } },
                { "endTimestamp", n => { EndTimestamp = n.GetDateTimeOffsetValue(); } },
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_entries>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_entries.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_errors>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_errors.CreateFromDiscriminatorValue)?.AsList(); } },
                { "eventID", n => { EventID = n.GetStringValue(); } },
                { "fingerprints", n => { Fingerprints = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "groupID", n => { GroupID = n.GetStringValue(); } },
                { "groupingConfig", n => { GroupingConfig = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_groupingConfig>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_groupingConfig.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "measurements", n => { Measurements = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_measurements>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_measurements.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "_meta", n => { Meta = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_meta>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_meta.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_metadata>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_metadata.CreateFromDiscriminatorValue); } },
                { "occurrence", n => { Occurrence = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_occurrence>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_occurrence.CreateFromDiscriminatorValue); } },
                { "packages", n => { Packages = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_packages>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_packages.CreateFromDiscriminatorValue); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "projectID", n => { ProjectID = n.GetStringValue(); } },
                { "sdk", n => { Sdk = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_sdk>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_sdk.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "startTimestamp", n => { StartTimestamp = n.GetDateTimeOffsetValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_tags>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_tags.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_user>(global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_breakdowns>("breakdowns", Breakdowns);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_context>("context", Context);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_contexts>("contexts", Contexts);
            writer.WriteStringValue("crashFile", CrashFile);
            writer.WriteStringValue("culprit", Culprit);
            writer.WriteDateTimeOffsetValue("dateCreated", DateCreated);
            writer.WriteDateTimeOffsetValue("dateReceived", DateReceived);
            writer.WriteStringValue("dist", Dist);
            writer.WriteDateTimeOffsetValue("endTimestamp", EndTimestamp);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_entries>("entries", Entries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_errors>("errors", Errors);
            writer.WriteStringValue("eventID", EventID);
            writer.WriteCollectionOfPrimitiveValues<string>("fingerprints", Fingerprints);
            writer.WriteStringValue("groupID", GroupID);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_groupingConfig>("groupingConfig", GroupingConfig);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("location", Location);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_measurements>("measurements", Measurements);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_meta>("_meta", Meta);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_occurrence>("occurrence", Occurrence);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_packages>("packages", Packages);
            writer.WriteStringValue("platform", Platform);
            writer.WriteStringValue("projectID", ProjectID);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_sdk>("sdk", Sdk);
            writer.WriteIntValue("size", Size);
            writer.WriteDateTimeOffsetValue("startTimestamp", StartTimestamp);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_tags>("tags", Tags);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Resolve_an_Event_ID_200_event_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
