// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Retrieve_a_Monitor_for_a_Project_200_config_schedule_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "crontab")]
        #pragma warning disable CS1591
        Crontab,
        #pragma warning restore CS1591
        [EnumMember(Value = "interval")]
        #pragma warning disable CS1591
        Interval,
        #pragma warning restore CS1591
    }
}
