// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Retrieve_a_Project_s_Symbol_Sources_200Member3 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bucket property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bucket { get; set; }
#nullable restore
#else
        public string Bucket { get; set; }
#endif
        /// <summary>The client_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientEmail { get; set; }
#nullable restore
#else
        public string ClientEmail { get; set; }
#endif
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_filters? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_filters Filters { get; set; }
#endif
        /// <summary>The has_index property</summary>
        public bool? HasIndex { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_public property</summary>
        public bool? IsPublic { get; set; }
        /// <summary>The layout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_layout? Layout { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_layout Layout { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The platforms property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Platforms { get; set; }
#nullable restore
#else
        public List<string> Platforms { get; set; }
#endif
        /// <summary>The prefix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prefix { get; set; }
#nullable restore
#else
        public string Prefix { get; set; }
#endif
        /// <summary>The private_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_private_key? PrivateKey { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_private_key PrivateKey { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bucket", n => { Bucket = n.GetStringValue(); } },
                { "client_email", n => { ClientEmail = n.GetStringValue(); } },
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_filters>(global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_filters.CreateFromDiscriminatorValue); } },
                { "has_index", n => { HasIndex = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_public", n => { IsPublic = n.GetBoolValue(); } },
                { "layout", n => { Layout = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_layout>(global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_layout.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "platforms", n => { Platforms = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "prefix", n => { Prefix = n.GetStringValue(); } },
                { "private_key", n => { PrivateKey = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_private_key>(global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_private_key.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bucket", Bucket);
            writer.WriteStringValue("client_email", ClientEmail);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_filters>("filters", Filters);
            writer.WriteBoolValue("has_index", HasIndex);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_public", IsPublic);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_layout>("layout", Layout);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("platforms", Platforms);
            writer.WriteStringValue("prefix", Prefix);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_private_key>("private_key", PrivateKey);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Retrieve_a_Project_s_Symbol_Sources_200Member3_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
