// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes List&lt;global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item&gt;, List&lt;global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1&gt;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActions : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type List&lt;global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item>? UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item> UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item { get; set; }
#endif
        /// <summary>Composed type representation for type List&lt;global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1>? UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1 { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1> UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActions();
            if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item> updateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1ItemValue)
            {
                result.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item = updateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1ItemValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1> updateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1Value)
            {
                result.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1 = updateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item>(null, UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsAnyOf1Item);
            }
            else if(UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1 != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1>(null, UpdateOrganizationWorkflows200ResponseItemActionFiltersItemActionsMember1);
            }
        }
    }
}
#pragma warning restore CS0618
