// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>
    /// Allows parameters to be defined in snake case, but passed as camel case.Errors are output in camel case.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Update_a_Monitor : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The configuration for the monitor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_config? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_config Config { get; set; }
#endif
        /// <summary>Disable creation of monitor incidents</summary>
        public bool? IsMuted { get; set; }
        /// <summary>Name of the monitor. Used for notifications. If not set the slug will be derived from your monitor name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the team or user that owns the monitor. (eg. user:51 or team:6)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>The project slug to associate the monitor to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Project { get; set; }
#nullable restore
#else
        public string Project { get; set; }
#endif
        /// <summary>Uniquely identifies your monitor within your organization. Changing this slug will require updates to any instrumented check-in calls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>Status of the monitor. Disabled monitors will not accept events and will not count towards the monitor quota.* `active`* `disabled`</summary>
        public global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor"/> and sets the default values.
        /// </summary>
        public Update_a_Monitor()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_status.Active;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_config>(global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_config.CreateFromDiscriminatorValue); } },
                { "is_muted", n => { IsMuted = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "project", n => { Project = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_config>("config", Config);
            writer.WriteBoolValue("is_muted", IsMuted);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("project", Project);
            writer.WriteStringValue("slug", Slug);
            writer.WriteEnumValue<global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Monitor_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
