// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>One of [Member, Team]* `Member`* `Team`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateOrganizationMonitorRequestAlertRuleTargetsItemTargetType
    {
        [EnumMember(Value = "Member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "Team")]
        #pragma warning disable CS1591
        Team,
        #pragma warning restore CS1591
    }
}
