// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateOrganizationDetectors200ResponseResponseJsonItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The conditionGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConditionGroup? ConditionGroup { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConditionGroup ConditionGroup { get; set; }
#endif
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConfig Config { get; set; }
#endif
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The dataSources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemDataSourcesItem>? DataSources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemDataSourcesItem> DataSources { get; set; }
#endif
        /// <summary>The dateCreated property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The dateUpdated property</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The latestGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemLatestGroup? LatestGroup { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemLatestGroup LatestGroup { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemOwner? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemOwner Owner { get; set; }
#endif
        /// <summary>The projectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The workflowIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? WorkflowIds { get; set; }
#nullable restore
#else
        public List<string> WorkflowIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseResponseJsonItem"/> and sets the default values.
        /// </summary>
        public UpdateOrganizationDetectors200ResponseResponseJsonItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseResponseJsonItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseResponseJsonItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseResponseJsonItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conditionGroup", n => { ConditionGroup = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConditionGroup>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConditionGroup.CreateFromDiscriminatorValue); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConfig>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConfig.CreateFromDiscriminatorValue); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "dataSources", n => { DataSources = n.GetCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemDataSourcesItem>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemDataSourcesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dateCreated", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "dateUpdated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "latestGroup", n => { LatestGroup = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemLatestGroup>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemLatestGroup.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemOwner>(global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemOwner.CreateFromDiscriminatorValue); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "workflowIds", n => { WorkflowIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConditionGroup>("conditionGroup", ConditionGroup);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemConfig>("config", Config);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemDataSourcesItem>("dataSources", DataSources);
            writer.WriteDateTimeOffsetValue("dateCreated", DateCreated);
            writer.WriteDateTimeOffsetValue("dateUpdated", DateUpdated);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemLatestGroup>("latestGroup", LatestGroup);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.UpdateOrganizationDetectors200ResponseItemOwner>("owner", Owner);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteStringValue("type", Type);
            writer.WriteCollectionOfPrimitiveValues<string>("workflowIds", WorkflowIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
