// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Update_a_Project : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;A JSON mapping of context types to lists of strings for their keys.E.g. `{&apos;user&apos;: [&apos;id&apos;, &apos;email&apos;]}`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project_highlightContext? HighlightContext { get; set; }
#nullable restore
#else
        public global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project_highlightContext HighlightContext { get; set; }
#endif
        /// <summary>A list of strings with tag keys to highlight on this project&apos;s issues.E.g. `[&apos;release&apos;, &apos;environment&apos;]`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? HighlightTags { get; set; }
#nullable restore
#else
        public List<string> HighlightTags { get; set; }
#endif
        /// <summary>Enables starring the project within the projects tab. Can be updated with **`project:read`** permission.</summary>
        public bool? IsBookmarked { get; set; }
        /// <summary>The name for the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The platform for the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>Automatically resolve an issue if it hasn&apos;t been seen for this many hours. Set to `0` to disable auto-resolve.</summary>
        public int? ResolveAge { get; set; }
        /// <summary>Enable on-demand source context fetching from SCM integrations for stack traces.</summary>
        public bool? ScmSourceContextEnabled { get; set; }
        /// <summary>Uniquely identifies a project and is used for the interface.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>Custom prefix for emails from this project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectPrefix { get; set; }
#nullable restore
#else
        public string SubjectPrefix { get; set; }
#endif
        /// <summary>The email subject to use (excluding the prefix) for individual alerts. Here are the list of variables you can use:- `$title`- `$shortID`- `$projectID`- `$orgID`- `${tag:key}` - such as `${tag:environment}` or `${tag:release}`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectTemplate { get; set; }
#nullable restore
#else
        public string SubjectTemplate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project"/> and sets the default values.
        /// </summary>
        public Update_a_Project()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "highlightContext", n => { HighlightContext = n.GetObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project_highlightContext>(global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project_highlightContext.CreateFromDiscriminatorValue); } },
                { "highlightTags", n => { HighlightTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "isBookmarked", n => { IsBookmarked = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "resolveAge", n => { ResolveAge = n.GetIntValue(); } },
                { "scmSourceContextEnabled", n => { ScmSourceContextEnabled = n.GetBoolValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "subjectPrefix", n => { SubjectPrefix = n.GetStringValue(); } },
                { "subjectTemplate", n => { SubjectTemplate = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Sentry.OpenApiClient.Models.Update_a_Project_highlightContext>("highlightContext", HighlightContext);
            writer.WriteCollectionOfPrimitiveValues<string>("highlightTags", HighlightTags);
            writer.WriteBoolValue("isBookmarked", IsBookmarked);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("platform", Platform);
            writer.WriteIntValue("resolveAge", ResolveAge);
            writer.WriteBoolValue("scmSourceContextEnabled", ScmSourceContextEnabled);
            writer.WriteStringValue("slug", Slug);
            writer.WriteStringValue("subjectPrefix", SubjectPrefix);
            writer.WriteStringValue("subjectTemplate", SubjectTemplate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
