// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sentry.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Configures multiple options for the Javascript Loader Script.- `Performance Monitoring`- `Debug Bundles &amp; Logging`- `Session Replay` - Note that the loader will load the ES6 bundle instead of the ES5 bundle.- `User Feedback` - Note that the loader will load the ES6 bundle instead of the ES5 bundle.- `Logs and Metrics` - Note that the loader will load the ES6 bundle instead of the ES5 bundle. Requires SDK &gt;= 10.0.0.```json{    \&quot;dynamicSdkLoaderOptions\&quot;: {        \&quot;hasReplay\&quot;: true,        \&quot;hasPerformance\&quot;: true,        \&quot;hasDebug\&quot;: true,        \&quot;hasFeedback\&quot;: true,        \&quot;hasLogsAndMetrics\&quot;: true    }}```&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateAClientKey_dynamicSdkLoaderOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The hasDebug property</summary>
        public bool? HasDebug { get; set; }
        /// <summary>The hasFeedback property</summary>
        public bool? HasFeedback { get; set; }
        /// <summary>The hasLogsAndMetrics property</summary>
        public bool? HasLogsAndMetrics { get; set; }
        /// <summary>The hasPerformance property</summary>
        public bool? HasPerformance { get; set; }
        /// <summary>The hasReplay property</summary>
        public bool? HasReplay { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Models.UpdateAClientKey_dynamicSdkLoaderOptions"/> and sets the default values.
        /// </summary>
        public UpdateAClientKey_dynamicSdkLoaderOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Models.UpdateAClientKey_dynamicSdkLoaderOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sentry.OpenApiClient.Models.UpdateAClientKey_dynamicSdkLoaderOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sentry.OpenApiClient.Models.UpdateAClientKey_dynamicSdkLoaderOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hasDebug", n => { HasDebug = n.GetBoolValue(); } },
                { "hasFeedback", n => { HasFeedback = n.GetBoolValue(); } },
                { "hasLogsAndMetrics", n => { HasLogsAndMetrics = n.GetBoolValue(); } },
                { "hasPerformance", n => { HasPerformance = n.GetBoolValue(); } },
                { "hasReplay", n => { HasReplay = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("hasDebug", HasDebug);
            writer.WriteBoolValue("hasFeedback", HasFeedback);
            writer.WriteBoolValue("hasLogsAndMetrics", HasLogsAndMetrics);
            writer.WriteBoolValue("hasPerformance", HasPerformance);
            writer.WriteBoolValue("hasReplay", HasReplay);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
