// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organization_id_or_slug}\discover\saved
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SavedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Sentry.OpenApiClient.api.Zero.organizations.item.discover.saved.item collection</summary>
        /// <param name="position">The ID of the Discover query you&apos;d like to retrieve.</param>
        /// <returns>A <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.Item.WithQuery_ItemRequestBuilder"/></returns>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.Item.WithQuery_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("query_id", position);
                return new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.Item.WithQuery_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.SavedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SavedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/discover/saved", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Discover.Saved.SavedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SavedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/discover/saved", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
