// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Autofix;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Events;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.ExternalIssues;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Hashes;
using Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Tags;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\0\organizations\{organization_id_or_slug}\issues\{issue_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithIssue_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The autofix property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Autofix.AutofixRequestBuilder Autofix
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Autofix.AutofixRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The EmptyPathSegment property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.EmptyPathSegmentRequestBuilder EmptyPathSegment
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.EmptyPathSegmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The externalIssues property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.ExternalIssues.ExternalIssuesRequestBuilder ExternalIssues
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.ExternalIssues.ExternalIssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hashes property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Hashes.HashesRequestBuilder Hashes
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Hashes.HashesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.WithIssue_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIssue_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/issues/{issue_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sentry.OpenApiClient.Api.Zero.Organizations.Item.Issues.Item.WithIssue_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIssue_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/0/organizations/{organization_id_or_slug}/issues/{issue_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
